# Continuous Bag of Words (CBOW) Model

In this exam, we will create a CBOW model using a sample Arabic traffic corpus. The corpus consists of sentences describing various traffic scenarios. The goal of the CBOW model is to predict a target word based on its surrounding context words.

# Importing Required Libraries

In this step, we import the necessary libraries to build and train the Continuous Bag of Words (CBOW) model.

- **TensorFlow and Keras**: Used to build the neural network model, including the layers like `Embedding`, `Dense`, and `Lambda`.
- **Tokenizer**: A utility from Keras for tokenizing and processing text data.
- **NumPy**: Used for handling numerical operations, particularly for processing arrays and data manipulation.

These libraries will provide the essential tools for text preprocessing and model development in the upcoming steps.

Add more if needed!


In [1]:
import tensorflow as tf
import numpy as np
import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from collections import Counter

# Preparing the Corpus

In this step, we initialize the corpus that will be used for training the Continuous Bag of Words (CBOW) model. The corpus consists of Arabic sentences, each of which describes different traffic scenarios.

- **Corpus**: A collection of traffic-related sentences in Arabic.

This step sets up the text data that we will use in the upcoming stages of tokenization and model training.

In [2]:
corpus = [
    "الطريق مزدحم اليوم بسبب الحادث المروري الذي حدث صباحاً ويؤدي إلى تأخير كبير في الوصول",
    "كان الطريق مزدحما للغاية والسيارات متوقفة تقريباً نتيجة الازدحام الشديد والحركة بطيئة جداً ولا تتحسن",
    "أنا أحب الذهاب إلى السوق في الصباح الباكر لتفادي الازدحام وشراء الخضروات الطازجة دون الانتظار في الطريق",
    "السيارات بطيئة بسبب الازدحام المروري في الشارع الرئيسي والتأخير في حركة المرور خلال ساعات الذروة",
    "هناك ازدحام مروري في الشارع بسبب أعمال البناء والحفريات التي تعطل حركة السيارات وتتسبب في تأخير كبير",
    "ازدحام السيارات يزداد في المساء عندما يبدأ الجميع بالعودة إلى منازلهم من العمل وتتوقف حركة المرور بالكامل",
    "الطريق السريع يشهد ازدحاما مستمرا خلال فترة الظهيرة بسبب الشاحنات الكبيرة التي تبطئ حركة السير",
    "الحافلات والسيارات عالقة في الازدحام المروري في المنطقة التجارية مما يؤدي إلى تأخير وصول الناس إلى وجهاتهم",
    "حركة المرور مزدحمة اليوم بسبب الفعاليات التي تقام في وسط المدينة مما يزيد من صعوبة الوصول إلى هناك",
    "كان من الصعب جدا القيادة على الطريق الرئيسي اليوم بسبب الازدحام الخانق الذي استمر طوال اليوم",
    "الطريق إلى المطار مزدحم اليوم بسبب الحوادث المتكررة والتأخيرات الكبيرة في حركة المرور على الطريق السريع",
    "الشارع مزدحم بالسيارات والحافلات الكبيرة مما يجعل التنقل بطيئًا جدًا ويزيد من وقت الوصول إلى العمل",
    "ازدحام السيارات في المدينة أصبح مشكلة كبيرة خاصة خلال ساعات الذروة حيث يصعب التحرك بسرعة",
    "تفاقم الازدحام في الطرق الجانبية بسبب إغلاق الطريق الرئيسي المؤدي إلى وسط المدينة لصيانة الجسر",
    "ازدحام مروري خانق يواجه السكان يوميًا خلال تنقلهم من وإلى العمل على الطرق السريعة المؤدية إلى المدينة",
    "التأخيرات المرورية اليوم ناجمة عن سوء الأحوال الجوية والضباب الذي يعيق الرؤية ويبطئ حركة السيارات",
    "حوادث السير المتكررة على الطريق الزراعي تؤدي إلى ازدحام مروري شديد وتأخير كبير في وصول السيارات",
    "كانت حركة السير اليوم غير منتظمة بسبب تنظيم حدث رياضي كبير أدى إلى إغلاق بعض الشوارع الرئيسية",
    "الأعمال الإنشائية في الشارع الرئيسي تسببت في اختناق مروري كامل وتباطؤ في حركة السيارات خلال النهار",
    "تراكم السيارات عند تقاطع الطرق الرئيسية أدى إلى ازدحام شديد وزيادة كبيرة في مدة الانتظار للوصول إلى الجهة المطلوبة"
]

# Defining Vocabulary and Model Parameters

In this step, we define key parameters that will be used to configure the CBOW model.

- **Vocabulary size**: We calculate the size of the vocabulary based on the number of unique words in the corpus. The `vocab_size` represents the total number of unique tokens (words) in the dataset plus one for padding.
  
- **Embedding size**: The `embedding_size` defines the dimensionality of the word embeddings. In this case, we set the embedding size to 10, meaning each word will be represented as a 10-dimensional vector in the embedding layer.

- **Window size**: The `window_size` defines how many words to the left and right of the target word are considered as context. Here, a window size of 2 means that two words before and two words after the target word will be used as context.

These parameters will play an essential role in shaping the CBOW model architecture.


In [3]:
tokens = []
for item in corpus:
    tokens.extend(item.lower().split())

vocab = Counter(tokens)

# key parameters
vocab_size = len(vocab) + 1  # +1 for paddin
embedding_size = 10
window_size = 2


print(f"Vocabulary Size: {vocab_size}")
print(f"Embedding Size: {embedding_size}")
print(f"Window Size: {window_size}")


word_to_index = {word: i for i, (word, _) in enumerate(vocab.items())}
word_to_index['<pad>'] = len(word_to_index)

print("Word to Index Mapping:", word_to_index)

Vocabulary Size: 179
Embedding Size: 10
Window Size: 2
Word to Index Mapping: {'الطريق': 0, 'مزدحم': 1, 'اليوم': 2, 'بسبب': 3, 'الحادث': 4, 'المروري': 5, 'الذي': 6, 'حدث': 7, 'صباحاً': 8, 'ويؤدي': 9, 'إلى': 10, 'تأخير': 11, 'كبير': 12, 'في': 13, 'الوصول': 14, 'كان': 15, 'مزدحما': 16, 'للغاية': 17, 'والسيارات': 18, 'متوقفة': 19, 'تقريباً': 20, 'نتيجة': 21, 'الازدحام': 22, 'الشديد': 23, 'والحركة': 24, 'بطيئة': 25, 'جداً': 26, 'ولا': 27, 'تتحسن': 28, 'أنا': 29, 'أحب': 30, 'الذهاب': 31, 'السوق': 32, 'الصباح': 33, 'الباكر': 34, 'لتفادي': 35, 'وشراء': 36, 'الخضروات': 37, 'الطازجة': 38, 'دون': 39, 'الانتظار': 40, 'السيارات': 41, 'الشارع': 42, 'الرئيسي': 43, 'والتأخير': 44, 'حركة': 45, 'المرور': 46, 'خلال': 47, 'ساعات': 48, 'الذروة': 49, 'هناك': 50, 'ازدحام': 51, 'مروري': 52, 'أعمال': 53, 'البناء': 54, 'والحفريات': 55, 'التي': 56, 'تعطل': 57, 'وتتسبب': 58, 'يزداد': 59, 'المساء': 60, 'عندما': 61, 'يبدأ': 62, 'الجميع': 63, 'بالعودة': 64, 'منازلهم': 65, 'من': 66, 'العمل': 67, 'وتتوقف': 68, 'بالكا

# Preparing Context-Target Pairs for CBOW

In this step, we generate the context-target pairs from the tokenized sequences to train the CBOW model.

- **Context words**: For each word in a sequence, the surrounding words (within the window size) are considered as context. The context consists of the words immediately before and after the target word.
  
- **Target word**: The word in the middle of the context window is treated as the target word that the model will learn to predict.

We iterate through each sequence, collecting the context words and corresponding target words:
- For each word in a sequence, we gather the surrounding words based on the defined window size.
- The middle word is the target, and the surrounding words form the context.

Finally:
- **`X`**: An array of context words.
- **`y`**: The target words are one-hot encoded, which means they are converted into a categorical format where each word is represented as a vector of length equal to the vocabulary size.

These context-target pairs will be used to train the CBOW model to predict a target word based on its context.


In [4]:
context_target_pairs = []

for i in range(len(tokens)):

    target_word = tokens[i]

    # context words
    start = max(0, i - window_size)
    end = min(len(tokens), i + window_size + 1)
    context_words = [tokens[j] for j in range(start, end) if j != i]

    # Combine them together
    context_target_pairs.append((context_words, target_word))

# context-target pairs
for context, target in context_target_pairs:
    print(f"Context: {context}, Target: {target}")

Context: ['مزدحم', 'اليوم'], Target: الطريق
Context: ['الطريق', 'اليوم', 'بسبب'], Target: مزدحم
Context: ['الطريق', 'مزدحم', 'بسبب', 'الحادث'], Target: اليوم
Context: ['مزدحم', 'اليوم', 'الحادث', 'المروري'], Target: بسبب
Context: ['اليوم', 'بسبب', 'المروري', 'الذي'], Target: الحادث
Context: ['بسبب', 'الحادث', 'الذي', 'حدث'], Target: المروري
Context: ['الحادث', 'المروري', 'حدث', 'صباحاً'], Target: الذي
Context: ['المروري', 'الذي', 'صباحاً', 'ويؤدي'], Target: حدث
Context: ['الذي', 'حدث', 'ويؤدي', 'إلى'], Target: صباحاً
Context: ['حدث', 'صباحاً', 'إلى', 'تأخير'], Target: ويؤدي
Context: ['صباحاً', 'ويؤدي', 'تأخير', 'كبير'], Target: إلى
Context: ['ويؤدي', 'إلى', 'كبير', 'في'], Target: تأخير
Context: ['إلى', 'تأخير', 'في', 'الوصول'], Target: كبير
Context: ['تأخير', 'كبير', 'الوصول', 'كان'], Target: في
Context: ['كبير', 'في', 'كان', 'الطريق'], Target: الوصول
Context: ['في', 'الوصول', 'الطريق', 'مزدحما'], Target: كان
Context: ['الوصول', 'كان', 'مزدحما', 'للغاية'], Target: الطريق
Context: ['كان

In [5]:
# One-hot encode target words
def one_hot_encode(target, vocab_size):
    one_hot_vector = np.zeros(vocab_size)
    index = word_to_index.get(target, -1)
    if index != -1:
        one_hot_vector[index] = 1
    return one_hot_vector

In [6]:
#  X and y arrays
X = []
y = []

max_len = 0

for context, target in context_target_pairs:
    X.append([word_to_index[word] for word in context])
    y.append(one_hot_encode(target, vocab_size))
    max_len = max(max_len, len(context))


# Padding context word sequences with zeros
for i in range(len(X)):
    X[i] = np.pad(X[i], (0, max_len - len(X[i])), 'constant')


X = np.array(X)
y = np.array(y)



print("\nX (Context Indices):")
print(X)

print("\ny (One-hot Encoded Targets):")
print(y)


X (Context Indices):
[[  1   2   0   0]
 [  0   2   3   0]
 [  0   1   3   4]
 ...
 [ 40 175 176 177]
 [175  10 177   0]
 [ 10 176   0   0]]

y (One-hot Encoded Targets):
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


# Building and Training the CBOW Model

In this step, we build and train the Continuous Bag of Words (CBOW) model using the context-target pairs created earlier.

1. **Model architecture**:
   - **Embedding layer**: This layer transforms the input context words into dense vector representations (embeddings) of size defined by `embedding_size`. The `input_dim` is set to the vocabulary size, and the `input_length` is twice the window size (since context consists of words from both sides of the target).
   
   - **Lambda layer**: This layer computes the mean of the context word embeddings. It averages the embeddings of the context words to generate a single representation that will be used to predict the target word.
   
   - **Dense layer**: This fully connected layer outputs a probability distribution over the vocabulary, using the softmax activation function. It predicts the most likely target word based on the context word embeddings.

2. **Compilation**:
   The model is compiled using the Adam optimizer and categorical cross-entropy as the loss function, which is suitable for multi-class classification tasks. Accuracy is used as a metric to evaluate the model's performance during training.

3. **Training the model**:
   The model is trained on the context-target pairs for 500 epochs. During each epoch, the model learns to predict the target word based on the context, refining its weights to improve accuracy.

4. **Saving the model weights**:
   After training, the model weights are saved to a file (`cbow_model.weights.h5`) for future use. This allows us to load the trained model later without retraining.

By the end of this step, the CBOW model will have learned to predict target words based on their surrounding context from the given corpus.

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Lambda
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K

# Build CBOW model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=window_size * 2))
model.add(Lambda(lambda x: K.mean(x, axis=1)))
model.add(Dense(vocab_size, activation='softmax'))



model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=50, verbose=1)

# Save
model.save_weights('cbow_model.weights.h5')

Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0052 - loss: 5.1873    
Epoch 2/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0355 - loss: 5.1820     
Epoch 3/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0581 - loss: 5.1773 
Epoch 4/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0749 - loss: 5.1727  
Epoch 5/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0577 - loss: 5.1683  
Epoch 6/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0745 - loss: 5.1620  
Epoch 7/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0894 - loss: 5.1555 
Epoch 8/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0730 - loss: 5.1522 
Epoch 9/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0772 - loss: 5.1477     
Epoch 10/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0757 - loss: 5.1443
Epoch 11/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0698 - loss: 5.1395 
Epoch 12/50
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy

# Predicting a Word Using the Trained CBOW Model

In this step, we define a function to predict a word based on a given context using the trained CBOW model.

1. **Function: `predict_word`**:
   - **Input**: The function takes a list of context words as input. The number of context words should match the expected size (2 times the window size).
   - **Context sequence conversion**: The input context words are tokenized into a sequence of integers using the same tokenizer that was used during training.
   - **Input validation**: The function checks whether the length of the context sequence matches the expected size (2 times the window size). If not, it prints an error message.
   - **Prediction**: The tokenized context is fed into the trained CBOW model, which predicts the probability distribution over the vocabulary.
   - **Retrieve predicted word**: The predicted word is the one with the highest probability. The function retrieves the word corresponding to the predicted index from the tokenizer's word index.

2. **Example**:
   - We provide a sample context: `['الحادث', 'بسبب', 'مزدحم', 'الطريق']`.
   - The function predicts the word that fits best in this context, based on the model's learned weights.
   - The predicted word is printed along with the input context.

This function allows us to test the CBOW model by predicting words based on their surrounding context from the corpus.

In [8]:
def predict_word(context_words, model, word_to_index, index_to_word, window_size):

    expected_size = window_size * 2
    if len(context_words) != expected_size:
        print(f"Error: Expected {expected_size} context words, but got {len(context_words)}.")
        return None

    # Convert
    context_indices = [word_to_index.get(word, -1) for word in context_words]

    # Check i words that were not in the vocabb
    if any(index == -1 for index in context_indices):
        print("Error: One or more context words are not in the vocabulary.")
        return None

    # Reshape the input to match the model's input shape
    context_array = np.array(context_indices).reshape(1, -1)
    predicted_probs = model.predict(context_array)


    predicted_index = np.argmax(predicted_probs)

    predicted_word = index_to_word.get(predicted_index, None)

    return predicted_word

In [9]:
# index-to-word mapping
index_to_word = {i: word for word, i in word_to_index.items()}

sample_context = ['الحادث', 'بسبب', 'مزدحم', 'الطريق']

# Predict word
predicted_word = predict_word(sample_context, model, word_to_index, index_to_word, window_size)

# result
if predicted_word:
    print(f"Input Context: {sample_context}")
    print(f"Predicted Word: {predicted_word}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
Input Context: ['الحادث', 'بسبب', 'مزدحم', 'الطريق']
Predicted Word: في
